name: "Claude Engineer"
description: "Run Claude Engineer prompts inside Home Assistant"
version: "0.1.0"
url: "https://github.com/drogfild/claude-engineer-ha-addon"
slug: "claude_engineer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 8000
panel_icon: mdi:robot
options:
  claude_api_key: ""
  homeassistant_api_key: ""
  claude_model: "claude-2"
schema:
  claude_api_key: str
  homeassistant_api_key: str
  claude_model: list(claude-2|claude-instant-1)
options:
  claude_api_key: ""
  homeassistant_api_key: ""
  claude_model: "claude-2"
schema:
  claude_api_key: str
  homeassistant_api_key: str
  claude_model: list(claude-2|claude-instant-1)